In [1]:
import numpy as np

In [3]:
x = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) 
y = np.array(([92], [86], [89]), dtype=float) 

In [4]:
print("Input:\n", x)
print("Output:\n", y)

Input:
 [[2. 9.]
 [1. 5.]
 [3. 6.]]
Output:
 [[92.]
 [86.]
 [89.]]


In [5]:
c = np.amax(x ,axis=0) 
print(c)

[3. 9.]


In [6]:
x = x/c

In [7]:
y = y/100

In [8]:
print("Normalised Input (x):\n", x)
print("Normalised Output (y):\n", y)

Normalised Input (x):
 [[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Normalised Output (y):
 [[0.92]
 [0.86]
 [0.89]]


In [9]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

In [10]:
def sigmoid_grad(x):
  return x*(1 - x)

In [11]:
epoch = 1000 
eta = 0.1 
input_neurons = 2 
hidden_neurons = 3 
output_neurons = 1 

In [12]:
wh = np.random.uniform(size=(input_neurons, hidden_neurons)) 
print("Weights Input to Hidden:\n", wh)

Weights Input to Hidden:
 [[0.09952028 0.56589119 0.90950061]
 [0.23463766 0.52464294 0.6270965 ]]


In [13]:
bh = np.random.uniform(size=(1, hidden_neurons)) 
print("Input Bias:\n", bh)

Input Bias:
 [[0.3644337  0.13953422 0.73685555]]


In [14]:
wout = np.random.uniform(size=(hidden_neurons, output_neurons)) 
print("Weights from hidden to Output Layer:\n", wout)

Weights from hidden to Output Layer:
 [[0.83913798]
 [0.73107411]
 [0.47317158]]


In [15]:
bout = np.random.uniform(size=(1, output_neurons)) 
print("Output Bias:\n", bout)

Output Bias:
 [[0.83243774]]


In [16]:
for i in range(epoch):
  print("\n---- EPOCH {} of {} ----\n".format(i+1, epoch))

  h_ip = np.dot(x, wh) + bh 
  print("\tEpoch {} h_ip:\n{}".format(i+1, h_ip))

  h_act = sigmoid(h_ip) 

  o_ip = np.dot(h_act, wout) + bout
  output = sigmoid(o_ip)

  Eo = y - output 
  out_grad = sigmoid_grad(output)
  d_output = Eo * out_grad
  print("\n\tEpoch {} output is:\n{}".format(i+1, d_output))

  Eh = d_output.dot(wout.T) 
  hidden_grad = sigmoid_grad(h_act) 
  d_hidden = Eh * hidden_grad
  wout += h_act.T.dot(d_output) * eta 
  wh += x.T.dot(d_hidden) * eta


---- EPOCH 1 of 1000 ----

	Epoch 1 h_ip:
[[0.66541821 1.04143796 1.97028578]
 [0.52796138 0.61963292 1.38840936]
 [0.62037908 1.05518737 2.06442049]]

	Epoch 1 output is:
[[ 0.00061431]
 [-0.00368635]
 [-0.00177562]]

---- EPOCH 2 of 1000 ----

	Epoch 2 h_ip:
[[0.66533358 1.04136963 1.97025742]
 [0.52791623 0.61959642 1.38839418]
 [0.62029476 1.05511987 2.06439291]]

	Epoch 2 output is:
[[ 0.00061999]
 [-0.0036827 ]
 [-0.00177154]]

---- EPOCH 3 of 1000 ----

	Epoch 3 h_ip:
[[0.6652493  1.04130158 1.97022917]
 [0.52787126 0.61956008 1.38837906]
 [0.62021076 1.05505262 2.06436544]]

	Epoch 3 output is:
[[ 0.00062565]
 [-0.00367906]
 [-0.00176747]]

---- EPOCH 4 of 1000 ----

	Epoch 4 h_ip:
[[0.66516536 1.04123379 1.97020103]
 [0.52782647 0.61952387 1.388364  ]
 [0.62012711 1.05498563 2.06433808]]

	Epoch 4 output is:
[[ 0.00063131]
 [-0.00367541]
 [-0.00176339]]

---- EPOCH 5 of 1000 ----

	Epoch 5 h_ip:
[[0.66508176 1.04116627 1.970173  ]
 [0.52778187 0.6194878  1.388349  ]
 [0.62004


	Epoch 364 output is:
[[ 0.00202744]
 [-0.0027177 ]
 [-0.00070442]]

---- EPOCH 365 of 1000 ----

	Epoch 365 h_ip:
[[0.65199115 1.02996276 1.96522475]
 [0.52082152 0.61351728 1.38570268]
 [0.60663344 1.04364528 2.0594714 ]]

	Epoch 365 output is:
[[ 0.00202948]
 [-0.00271623]
 [-0.0007028 ]]

---- EPOCH 366 of 1000 ----

	Epoch 366 h_ip:
[[0.65198745 1.02995655 1.96522022]
 [0.52081966 0.61351402 1.38570026]
 [0.60662808 1.0436382  2.05946686]]

	Epoch 366 output is:
[[ 0.00203152]
 [-0.00271476]
 [-0.0007012 ]]

---- EPOCH 367 of 1000 ----

	Epoch 367 h_ip:
[[0.65198387 1.02995041 1.96521571]
 [0.52081786 0.6135108  1.38569786]
 [0.60662282 1.04363121 2.05946236]]

	Epoch 367 output is:
[[ 0.00203355]
 [-0.0027133 ]
 [-0.0006996 ]]

---- EPOCH 368 of 1000 ----

	Epoch 368 h_ip:
[[0.6519804  1.02994436 1.96521124]
 [0.52081612 0.61350763 1.38569547]
 [0.60661767 1.0436243  2.05945789]]

	Epoch 368 output is:
[[ 0.00203556]
 [-0.00271184]
 [-0.00069801]]

---- EPOCH 369 of 1000 ----

	

 [0.6078509  1.04376457 2.05895594]]

	Epoch 628 output is:
[[ 0.00235138]
 [-0.00248072]
 [-0.00044664]]

---- EPOCH 629 of 1000 ----

	Epoch 629 h_ip:
[[0.65372418 1.03036746 1.96473097]
 [0.52177941 0.61375176 1.38544079]
 [0.60786235 1.04377017 2.05895571]]

	Epoch 629 output is:
[[ 0.00235202]
 [-0.00248024]
 [-0.00044613]]

---- EPOCH 630 of 1000 ----

	Epoch 630 h_ip:
[[0.65373773 1.03037427 1.96473089]
 [0.52178678 0.61375548 1.38544076]
 [0.60787383 1.04377578 2.05895549]]

	Epoch 630 output is:
[[ 0.00235266]
 [-0.00247977]
 [-0.00044562]]

---- EPOCH 631 of 1000 ----

	Epoch 631 h_ip:
[[0.65375132 1.03038111 1.96473082]
 [0.52179416 0.61375921 1.38544073]
 [0.60788534 1.04378143 2.05895528]]

	Epoch 631 output is:
[[ 0.00235329]
 [-0.00247929]
 [-0.00044511]]

---- EPOCH 632 of 1000 ----

	Epoch 632 h_ip:
[[0.65376493 1.03038798 1.96473076]
 [0.52180156 0.61376295 1.38544071]
 [0.60789689 1.04378709 2.05895508]]

	Epoch 632 output is:
[[ 0.00235392]
 [-0.00247882]
 [-0.00044

	Epoch 954 h_ip:
[[0.65923972 1.03343102 1.96498785]
 [0.52476751 0.61541306 1.38558143]
 [0.61268075 1.04642271 2.05915794]]

	Epoch 954 output is:
[[ 0.00245652]
 [-0.00239895]
 [-0.00036132]]

---- EPOCH 955 of 1000 ----

	Epoch 955 h_ip:
[[0.65925872 1.03344201 1.96498916]
 [0.52477779 0.61541902 1.38558215]
 [0.61269756 1.0464324  2.05915907]]

	Epoch 955 output is:
[[ 0.00245665]
 [-0.00239884]
 [-0.00036121]]

---- EPOCH 956 of 1000 ----

	Epoch 956 h_ip:
[[0.65927773 1.03345301 1.96499047]
 [0.52478807 0.61542497 1.38558286]
 [0.61271438 1.04644209 2.0591602 ]]

	Epoch 956 output is:
[[ 0.00245677]
 [-0.00239873]
 [-0.00036111]]

---- EPOCH 957 of 1000 ----

	Epoch 957 h_ip:
[[0.65929674 1.03346402 1.96499179]
 [0.52479836 0.61543093 1.38558357]
 [0.61273121 1.04645179 2.05916133]]

	Epoch 957 output is:
[[ 0.0024569 ]
 [-0.00239862]
 [-0.000361  ]]

---- EPOCH 958 of 1000 ----

	Epoch 958 h_ip:
[[0.65931576 1.03347503 1.96499311]
 [0.52480865 0.61543689 1.38558429]
 [0.6127480

In [17]:
print("Actual Output:\n", y)

Actual Output:
 [[0.92]
 [0.86]
 [0.89]]


In [18]:
print("Predicted Output\n", output)

Predicted Output
 [[0.89401794]
 [0.88321254]
 [0.89375873]]
